config/routes.rb
#rails generate clearance:routes

Rails.application.routes.draw do

  get 'payment/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :show] do
    resource :password, controller: "clearance/passwords", only: [:create, :edit, :update]
    resources :reservations
  end
  #resource will not create :id/ in path and is applicable here cause password is a column, not a model/table
  #resources will create :id/ in path, and relates to the database's :id

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	root "welcome#index"

	resources :products

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resource :reservations, only: [:new, :create] do
      resource :payments, controller: "payments", only: [:new, :create]
    end
  end

  get "/users/:user_id/listings" => "users#user_listing", as: "user_listing"

  post '/listings/:listing_id/reservations/payments/checkout' => "payments#checkout", controller: "payments", as: "payments_checkout"

  post 'search', to: "listings#search"

  post 'filter', to: "listings#filter"
  
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  include PgSearch

  has_many :reservations

  scope :location, -> (location) { where location: location }
  scope :price_per_night, -> (price_per_night) { where price_per_night: price_per_night }
  scope :smoking, -> (smoking) { where smoking: smoking }

  delegate :user_name, :to => :user, :prefix => true

  def self.search_location(query)
    where("location ILIKE :location", location: "%#{query}%").map do |record|
      record.location 
    end
  end

  def self.find_listings(parameters)
    
    listings = Listing.where(nil)
    
    parameters.each do |key, value|
      listings = listings.public_send(key, value) if value.present?
    end
    listings
    
  end


  

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	def new
		@listing = Listing.new
	end

	def create
		@listing = Listing.new(listing_params)

		@listing.save
		
		redirect_to "/", notice: "Listing saved!"
	end

	def index	
    parameters = filtering_params(params)
    #params = params = { listing: { title: }}
    @listings = Listing.find_listings(parameters)
    
    @listings = @listings.order(id: :desc).page params[:page]
	end

	def edit
		# allowed?(action: @listing, user: current_user)
		@listing = Listing.find(params[:id])
	end

	def update
		@listing = Listing.find(params[:id])
		@listing.update(update_listing_params)

		redirect_to listings_path
	end

	def search
    cities = Listing.search_location(params["query"])
    render json: cities 
  end

private

	def listing_params
		byebug
    params.require(:listing).permit(:title, :description, :price_per_night, :smoking, :location, :user_id, :image, amenities: [])
	
	end

	def update_listing_params
		byebug
    params.require(:listing).permit(:title, :description, :price_per_night, :smoking, :location)
	end

	def filtering_params(params)
    byebug
    params.slice(:location, :smoking, :price_per_night)
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<h2> Edit Property </h2> 

<%= form_for @listing, url: {action: "update"} do |p| %>

<%= p.hidden_field :user_id, :value => current_user.id %>
	
	Title:
	<%= p.text_field :title %>
	<br/>
	Location:
	<%= p.text_field :location %>
	<br/>
	Description:
	<%= p.text_field :description %>
	<br/>
	Price Per Night:
	<%= p.number_field :price_per_night %>
	<br/>
	<%= p.submit %>
<% end %>

app/views/listings/index.html.erb
Create new listing <%= link_to "here", "/listings/new" %>

<h2> All Listings </h2>

<h5> Search </h5>
<%= form_tag listings_path, :method => 'get' do %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <br/>
    Location: <%= text_field_tag :location, params[:location]  %> <br/>
    User: <%= text_field_tag :user, params[:user]  %> <br/>
    Price Per Night: <%= text_field_tag :price_per_night, params[:price_per_night]  %> <br/>
    Smoking: <%= text_field_tag :smoking, params[:smoking]  %>
    <%= submit_tag "Search", :name => nil, :id=>"button" %>
<% end %>
<br/>
<br/>


<h5> All Listings </h5>

<table>
	<tr>
		<th> Id </th>
		<th> Title </th>
		<th> Location </th>
		<th> Description </th>
		<th> Price/Night </th>
		<th> Smoking </th>
		<th> By User </th>
    <th> Image </th>
    <th> Book </th>
    <th> Edit (Permissions needed) </th>
	</tr>
	<% @listings.each do |listing| %>
		<tr id="list">	
			<td> <%= listing.id %> </td>
			<td> <%= listing.title %> </td>
			<td> <%= listing.location %> </td>
			<td> <%= listing.description %> </td>
			<td> <%= listing.price_per_night %> </td>
			<td> <%= listing.smoking %> </td>
			<td> <%= listing.user.name %> </td>
      <td> <img src ="<%= listing.image_url.to_s %>" width="100" height="100"> </td>
      <td> <%= link_to 'Book', new_listing_reservations_path(listing) %></td>
			<td> <%= link_to 'Edit', edit_listing_path(listing) %> </td>
		</tr>
	<% end %> 
</table>

app/views/listings/new.html.erb
<h2> List Your Property </h2> 

<%= form_for @listing, url: {action: "create"} do |p| %>

<%= p.hidden_field :user_id, :value => current_user.id %>
<!-- user_id is the name of the field or key, just like :title. -->
<!-- value is set to current_user.id that matches up to the name "user_id". So technically in text_field, we could have paired it with a pre-defined value -->

	Title:
	<%= p.text_field :title %>
	<br/>
	Location:
	<%= p.text_field :location %>
	<br/>
	Description:
	<%= p.text_field :description %>
	<br/>
	Price Per Night:
	<%= p.number_field :price_per_night %>
	<br/>
	Smoking (Use 1 for yes, 0 for no):
	<%= p.number_field :smoking %>
	<br/>
	Amenities:
	<br/>
	- Gym <%= p.check_box :amenities, {multiple: true}, "gym", nil %>
	<br/>
	- Sauna <%= p.check_box :amenities, {multiple: true}, "sauna", nil %>
	<br/>
	- Pool <%= p.check_box :amenities, {multiple: true}, "pool", nil %>
	<br/>
	Upload Image here:
	<%= p.file_field :image %>
	<br/>
	<%= p.submit %>
<% end %>