config/routes.rb
#rails generate clearance:routes

Rails.application.routes.draw do

  get 'payment/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :show] do
    resource :password, controller: "clearance/passwords", only: [:create, :edit, :update]
    resources :reservations
  end
  #resource will not create :id/ in path and is applicable here cause password is a column, not a model/table
  #resources will create :id/ in path, and relates to the database's :id

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	root "welcome#index"

	resources :products

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resource :reservations, only: [:new, :create] do
      resource :payments, controller: "payments", only: [:new, :create]
    end
  end

  get "/users/:user_id/listings" => "users#user_listing", as: "user_listing"

  post '/listings/:listing_id/reservations/payments/checkout' => "payments#checkout", controller: "payments", as: "payments_checkout"

  post 'search', to: "listings#search"

  post 'filter', to: "listings#filter"
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  
  end
end

#class is a folder, method is the page.
#So in this instance, Welcome Controller >> Views >> Welcome
#and then looks for file Index

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>Welcome to Jun's Test Pairbnb!</h1>

<% flash.each do |key, value| -%>
  <div class="<%= flash_class(key) %>"><%= value %></div>
<% end %>

Please sign in here:
<ul>
	<li> Sign in with <%= link_to "Facebook", "/auth/facebook" %> </li>
	<li> Sign in with <%= link_to "Onsite Logins", "/sign_in" %> </li>
</ul>

View all existing listings <%= link_to "here", listings_path %>
<br/>
Create new listing <%= link_to "here", new_listing_path %>
<br/>
<p>
<% if current_user %>
  View your trip reservations <%= link_to "here", user_reservations_path(current_user) %>
  <br/>
  View reservations on your listing <%= link_to "here", user_listing_path(current_user) %>
<% end %>
</p>

<div id="home">
  <h2>Search For location Using AJAX</h2>
  <div id="search-div">
    <%= form_tag search_path do %>
      <%= label_tag "search" %>
      <%= text_field_tag "search", nil, list: "list" %>
      <datalist id="list"></datalist>
    <% end %>
  </div>
</div>