config/routes.rb
#rails generate clearance:routes

Rails.application.routes.draw do

  get 'payment/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :show] do
    resource :password, controller: "clearance/passwords", only: [:create, :edit, :update]
    resources :reservations
  end
  #resource will not create :id/ in path and is applicable here cause password is a column, not a model/table
  #resources will create :id/ in path, and relates to the database's :id

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	root "welcome#index"

	resources :products

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resource :reservations, only: [:new, :create] do
      resource :payments, controller: "payments", only: [:new, :create]
    end
  end

  get "/users/:user_id/listings" => "users#user_listing", as: "user_listing"

  post '/listings/:listing_id/reservations/payments/checkout' => "payments#checkout", controller: "payments", as: "payments_checkout"

  post 'search', to: "listings#search"

  post 'filter', to: "listings#filter"
  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @client_token = Braintree::ClientToken.generate
  end

  def checkout
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    result = Braintree::Transaction.sale(
     :amount => "10.00", #this is currently hardcoded
     :payment_method_nonce => nonce_from_the_client,
     :options => {
        :submit_for_settlement => true
      }
     )

    if result.success?
      redirect_to :root, :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<h2>Payment Details</h2>

<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>"><%= value %></div>
<% end %>

<div class="demo-frame">

  <%= form_for :checkout_form, url: payments_checkout_path, html: { id: "cardForm"} do |form| %>
  <%= form.hidden_field :client_token, :value => @client_token, id: "hidden-field" %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>
  <% end %>


</div>