config/routes.rb
#rails generate clearance:routes

Rails.application.routes.draw do

  get 'payment/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :show] do
    resource :password, controller: "clearance/passwords", only: [:create, :edit, :update]
    resources :reservations
  end
  #resource will not create :id/ in path and is applicable here cause password is a column, not a model/table
  #resources will create :id/ in path, and relates to the database's :id

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	root "welcome#index"

	resources :products

	get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resource :reservations, only: [:new, :create] do
      resource :payments, controller: "payments", only: [:new, :create]
    end
  end

  get "/users/:user_id/listings" => "users#user_listing", as: "user_listing"

  post '/listings/:listing_id/reservations/payments/checkout' => "payments#checkout", controller: "payments", as: "payments_checkout"

  post 'search', to: "listings#search"

  post 'filter', to: "listings#filter"
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

  <!-- BRAINTREE: Load the Client component. -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

  <!-- BRAINTREE: Load the Hosted Fields component. -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

  

</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      You are currently signed in as <%= current_user.email %>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <%= yield %>
</body>
</html>